version: '3.7'
services:
  mongodb:
    image: mongo:latest
    user: root
    container_name: mongodb_boot
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/kjcaway/mnt/mongodb/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
