version: '3.7'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - 1433:1433
    volumes:
      - /Users/kjcaway/mnt/sqlserver:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: root
