version: '3.7'
services:
  db:
    image: mariadb:10.5
    container_name: mariadb_boot
    hostname: mariadb_boot
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /home/kang/mariadb/data:/var/lib/mysql
      - /home/kang/mariadb/config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul