version: '3.7'
services:
  db:
    image: mysql:8.0.22
    container_name: mysql_boot
    hostname: mysql_boot
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /home/ubun2/mysql/data:/var/lib/mysql
      - /home/ubun2/mysql/config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul