version: "3.8"
services:
    redis:
        image: redis:6.2.6-alpine
        ports:
            - 6379:6379
        container_name: redis_boot
        hostname: redis_boot
        command: redis-server
        volumes:
            - /home/ubun2/redis/data:/data
            - ./redis.conf:/usr/local/conf/redis.conf
        restart: always
